// src/vue/components/item.tsx
import wrap from '@vue/web-component-wrapper'
import { boundMethod } from 'autobind-decorator'
import Vue from 'vue'
import Component from 'vue-class-component'
import { Prop } from 'vue-property-decorator'

import getReact from '../../getReact'

@Component
class ItemComponent extends Vue {
  @Prop({
    type: String,
    default: 'Hello world!',
  })
  message!: string

  @boundMethod
  onClick(e: Event) {
    e.stopPropagation()

    const host = e.currentTarget || e.target

    if (host instanceof HTMLElement) {
      const react = document.createElement('react-item')
      react.setAttribute('message', 'I\'m on React!')
      react.slot = 'bottom'
      host.appendChild(react)
    }
  }

  render(overrideWithVue: Vue.CreateElement) {
    const React = getReact(overrideWithVue)

    const onClick =
      this.onClick as unknown as (event: React.MouseEvent<HTMLElement, MouseEvent>) => void

    return (
      <section onClick={onClick}>
        <h1>{this.message}</h1>
        <p>Click to bring a React component.</p>
        <slot name="bottom"></slot>
        <style>{`
          :host > section {
            background: #35495e;
            border-radius: 8px;
            color: #41b883;
            cursor: pointer;
            margin: 8px 0 0;
            padding: 8px;
          }
        `}</style>
      </section>
    ) as unknown as Vue.VNode
  }
}

const Item = wrap(Vue, ItemComponent)

export const name = 'vue-item'

export default Item

// src/react/components/item.tsx
import { DOMModel, byAttrVal, createCustomElement } from '@adobe/react-webcomponent'
import { boundMethod } from 'autobind-decorator'
import React from 'react'

type ItemProps = {
  message: string
}

class ItemModel extends DOMModel {
  @byAttrVal
  message: string = 'Hello world!'
}

class ItemComponent extends React.Component<ItemProps> {
  constructor(props: ItemProps) {
    super(props)
  }

  @boundMethod
  onClick(e: React.MouseEvent<HTMLElement, MouseEvent>) {
    e.stopPropagation()

    const root = (e.currentTarget || e.target).parentNode

    if (root instanceof ShadowRoot) {
      const vue = document.createElement('vue-item')
      vue.setAttribute('message', 'I\'m on Vue.js!')
      vue.slot = 'bottom'
      root.host.appendChild(vue)
    }
  }

  render() {
    return (
      <section onClick={this.onClick}>
        <h1>{this.props.message}</h1>
        <p>Click to bring a Vue.js component.</p>
        <slot name="bottom"></slot>
        <style>{`
          :host > section {
            background: #20232a;
            border-radius: 8px;
            color: #61dafb;
            cursor: pointer;
            margin: 8px 0 0;
            padding: 8px;
          }
        `}</style>
      </section>
    )
  }
}

const Item = createCustomElement(ItemComponent, ItemModel, 'openShadowRoot')

export const name = 'react-item'

export default Item
